apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/version: v13.32.0
  name: socketio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: socketio
      app.kubernetes.io/name: socketio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: socketio
        app.kubernetes.io/name: socketio
    spec:
      containers:
      - image: frappe/frappe-socketio:v13.31.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        name: socketio
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - CAP_CHOWN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/frappe/frappe-bench/sites
          name: sites-dir
        - mountPath: /home/frappe/frappe-bench/logs
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 1000
      serviceAccount: erpnext
      serviceAccountName: erpnext
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sites-dir
        persistentVolumeClaim:
          claimName: erpnext
      - name: logs
        persistentVolumeClaim:
          claimName: erpnext-logs
